---
drake_cache: '.server'
---

```{r makecondition}
library(shiny)
shiny::reactiveConsole(T) # for developing stage. Should mark off when launching the product.
library(ggplot2)
library(dplyr)
library(shiny)
library(htmltools)
library(econR)
library(ggplot2)
library(dplyr)
library(readxl)
library(stringr)
library(sysfonts)
library(showtext)
library(tidyselect)
library(purrr)
library(plotly)
library(readxl)
library(readr)
library(patchwork)
library(leaflet)

load("support/data/finaldata.RData")
```

```{r, reactive = T}
reactive({
  choosen_school_data <- school_109 %>% filter(縣市學校名稱 == input_selectcity)

  county_name <- choosen_school_data %>% select(縣市名稱) %>% unlist() %>% unname()

  school_name <- choosen_school_data %>% select(學校名稱) %>% unlist() %>% unname()

  choosen_school_lng <- choosen_school_data %>% select(經度) %>% unlist() %>% unname()

  choosen_school_lat <- choosen_school_data %>% select(緯度) %>% unlist() %>% unname()

  city_county<- choosen_school_data %>% select(縣市鄉鎮) %>% unlist() %>% unname()

  sports %>% filter(縣市鄉鎮 == city_county) -> sports_data_leaflet

  library_data %>% filter(縣市鄉鎮 == city_county) ->  library_data_leaflet
})
```


## Input 

```{r makecondition_input}
input_bins = 30

input_selectcity1 = "宜蘭縣"
```


## Output rendering

  * must have `render_outputId` and `output_outputId` objects.
  
  * `render_outputId` has render function as its value, which will be used to generate proper server.R

```{r render_distPlot}
render_distPlot <- shiny::renderPlot
```

```{r output_distPlot}
output_distPlot <-  {
    ggplot(data=faithful) +
      geom_histogram(
        aes(x=eruptions), bins=as.numeric(input_bins)
      )
}

```

### 縣市

#### text
```{r render_desctextcity}
render_desctextcity <- renderText
```

```{r output_desctextcity}
output_desctextcity <- paste0(
  input_selectcity1, "總計有",
  school_109_bycity %>% filter(縣市名稱 == input_selectcity1) %>% select(學校數總計) %>% unlist() %>% unname() %>% unique(), "間偏遠地區學校（偏校），且其偏校總數排名為全台縣市第",
  school_109_bycity %>% filter(縣市名稱 == input_selectcity1) %>% select(排名) %>% unlist() %>% unname() %>% unique(), "名。"
)
```

```{r render_desctextcity2}
render_desctextcity2 <- renderText
```

```{r output_desctextcity2}
output_desctextcity2 <- paste0(
  "偏遠學校數：",
  if(length(
    school_109_bycity %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "偏遠") %>% select(學校數) %>% unlist() %>% unname()) == 0
    ){0}else{
    school_109_bycity %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "偏遠") %>% select(學校數) %>% unlist() %>% unname() },
  "\n","特偏學校數：",
  if(
    length(school_109_bycity %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "特偏") %>% select(學校數) %>% unlist() %>% unname()) == 0 
    ){0}else{
    school_109_bycity %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "特偏") %>% select(學校數) %>% unlist() %>% unname() },
  "\n", "極偏學校數：",
  if(
    length(school_109_bycity %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "極偏") %>% select(學校數) %>% unlist() %>% unname()) == 0 
    ){0}else{
    school_109_bycity %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "極偏") %>% select(學校數) %>% unlist() %>% unname() }
  
)
```

```{r render_citymaptitle}
render_citymaptitle <- renderText
```

```{r output_citymaptitle}
output_citymaptitle <- paste0(input_selectcity1,"偏遠地區學校位置")
```

#### plotly
```{r render_plotlycity}
render_plotlycity <- renderPlotly
```

```{r output_plotlycity}
output_plotlycity <- school_109_bycity_plotly
```

#### leaflet

```{r render_leafletplotcity}
render_leafletplotcity <- renderLeaflet
```

```{r icons1}
icons1 <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion'
)
```

```{r icons2}
icons2 <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = "red"
)
```

```{r icons3}
icons3 <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = "green"
)
```

```{r output_leafletplotcity}
output_leafletplotcity <- {
  leaflet() %>%
    addTiles() %>%
    setView(
      lng = head(school_109 %>% filter(縣市名稱 == input_selectcity1) %>% select(經度),1) %>% unlist() %>% unname(),
      lat = head(school_109 %>% filter(縣市名稱 == input_selectcity1) %>% select(緯度),1) %>% unlist() %>% unname(),
      zoom = 9
    ) %>% 
    addAwesomeMarkers(
      lng = school_109 %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "偏遠") %>% select(經度) %>% unlist() %>% unname(),
      lat = school_109 %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "偏遠") %>% select(緯度) %>% unlist() %>% unname(),
      popup = paste0(
        school_109 %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "偏遠") %>% select(學校名稱) %>% unlist() %>% unname(), "：偏遠"
      ),
      icon = icons1
    ) %>% 
    addAwesomeMarkers(
      lng = school_109 %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "極偏") %>% select(經度) %>% unlist() %>% unname(),
      lat = school_109 %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "極偏") %>% select(緯度) %>% unlist() %>% unname(),
      popup = paste0(
        school_109 %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "極偏") %>% select(學校名稱) %>% unlist() %>% unname(), "：極偏"
      ),
      icon = icons2
    ) %>% 
    addAwesomeMarkers(
      lng = school_109 %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "特偏") %>% select(經度) %>% unlist() %>% unname(),
      lat = school_109 %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "特偏") %>% select(緯度) %>% unlist() %>% unname(),
      popup = paste0(
        school_109 %>% filter(縣市名稱 == input_selectcity1 & 地區屬性 == "特偏") %>% select(學校名稱) %>% unlist() %>% unname(), "：特偏"
      ),
      icon = icons3
    )
}
```


### 個別學校
#### text
```{r render_desctext}
render_desctext <- renderText
```

```{r output_desctext}
output_desctext <- paste0(
  input_selectcity, "為分級上的", 
  school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(地區屬性) %>% unlist() %>% unname(),
  "學校，位處",
  school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(縣市鄉鎮) %>% unlist() %>% unname(),
  if(is.na(school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(原住民鄉分類) %>% unlist() %>% unname())){"。"}else{
    paste0("，且其為原住民鄉分類上的",
    school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(原住民鄉分類) %>% unlist() %>% unname(),"。")
  }
)
```

```{r render_desctext2}
render_desctext2 <- renderText
```

```{r output_desctext2}
output_desctext2 <- paste0(
    "學生總計：",
    school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(學生數總計) %>% unlist() %>% unname(),
    "\n", "班級數總計：",
    school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(班級數) %>% unlist() %>% unname(),
    if(
      is.na(school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(原住民學生比率) %>% unlist() %>% unname())){
    "\n"
  }else{
    paste0("\n","原住民學生比率：",
  school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(原住民學生比率) %>% unlist() %>% unname(),"\n")},
  "學校網址：",
  school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(網址) %>% unlist() %>% unname()
  )
```

```{r render_maptitle}
render_maptitle <- renderText
```

```{r output_maptitle}
output_maptitle <- paste0(input_selectcity,"—",
        school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(地區屬性) %>% unlist() %>% unname(),"學校位置")
```

```{r render_allplotlytitle}
render_allplotlytitle <- renderText
```

```{r output_allplotlytitle}
output_allplotlytitle <- paste0(
  input_selectcity,"—","所屬地區指標"
)
```


#### leaflet
```{r render_leafletPlot}
render_leafletPlot <- renderLeaflet
```

```{r output_leafletPlot}
output_leafletPlot <- {
  leaflet() %>% 
  addTiles() %>% 
  setView(
    lng = school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(經度) %>% unlist() %>% unname(), 
    lat= school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(緯度) %>% unlist() %>% unname(),
    zoom = 11)    %>% 
    addMarkers(
      lng = school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(經度) %>% unlist() %>% unname(),
      lat= school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(緯度) %>% unlist() %>% unname(),
      popup = paste0(input_selectcity,":",
        school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(地區屬性) %>% unlist() %>% unname()))  %>% 
    addCircleMarkers(
      data = sports %>% filter(
        縣市鄉鎮 == school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(縣市鄉鎮) %>% unlist() %>% unname()
      ),radius = 8, stroke =T, fillOpacity =  0.7,color = "#4d9221", 
      popup = sports %>% filter(
        縣市鄉鎮 == school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(縣市鄉鎮) %>% unlist() %>% unname()
      ) %>% select(場館名稱) %>% unlist() %>% unname()
    ) %>% 
    addCircleMarkers(
      data = library_data %>% filter(
        縣市鄉鎮 == school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(縣市鄉鎮) %>% unlist() %>% unname()
      ),radius = 8, stroke =T, fillOpacity =  0.7,color = "#fdae61", 
      popup = library_data %>% filter(
        縣市鄉鎮 == school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(縣市鄉鎮) %>% unlist() %>% unname()
      ) %>% select(圖書館名稱) %>% unlist() %>% unname()
    )
}
```

#### plotly

```{r render_plotly1}
render_plotly1 <- renderPlotly
```

```{r output_plotly1}
output_plotly1 <- culture_lib_spt_plot_1_plotly %>% 
  add_trace(
    x=1,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(鄉鎮圖書館體育館總和) %>% unlist() %>% unname(),
    type="scatter",mode="markers", name = "該校所屬鄉鎮市區", marker = list(color = "red")
    ) %>% 
  add_trace(
    x=2,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(鄉鎮圖書館體育館總和) %>% unlist() %>% unname(),
    type="scatter",mode="markers",name = "該校所屬鄉鎮市區", marker = list(color = "red"))
```

```{r render_plotly2}
render_plotly2 <- renderPlotly
```

```{r output_plotly2}
output_plotly2 <- life_density10909_plot_2_plotly %>% 
  add_trace(
    x=1,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(村里人口密度) %>% unlist() %>% unname(),
    type="scatter",mode="markers", name = "該校所屬村里", marker = list(color = "red")
    ) %>% 
  add_trace(
    x=2,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(村里人口密度) %>% unlist() %>% unname(),
    type="scatter",mode="markers",name = "該校所屬村里", marker = list(color = "red"))
```

```{r render_plotly3}
render_plotly3 <- renderPlotly
```

```{r output_plotly3}
output_plotly3 <- life_conv_finance_plot_3_plotly %>% 
  add_trace(
    x=1,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(鄉鎮便利金融) %>% unlist() %>% unname(),
    type="scatter",mode="markers", name = "該校所屬鄉鎮", marker = list(color = "red")
    ) %>% 
  add_trace(
    x=2,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(鄉鎮便利金融) %>% unlist() %>% unname(),
    type="scatter",mode="markers",name = "該校所屬鄉鎮", marker = list(color = "red"))
```

```{r render_plotly4}
render_plotly4 <- renderPlotly
```

```{r output_plotly4}
output_plotly4 <- life_hospital_plot_4_plotly %>% 
  add_trace(
    x=1,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(醫療院所家數) %>% unlist() %>% unname(),
    type="scatter",mode="markers", name = "該校所屬鄉鎮", marker = list(color = "red")
    ) %>% 
  add_trace(
    x=2,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(醫療院所家數) %>% unlist() %>% unname(),
    type="scatter",mode="markers",name = "該校所屬鄉鎮", marker = list(color = "red"))
```

```{r render_plotly5}
render_plotly5 <- renderPlotly
```

```{r output_plotly5}
output_plotly5 <- digital_plot_5_plotly %>% 
  add_trace(
    x=1,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(鄉鎮基地台) %>% unlist() %>% unname(),
    type="scatter",mode="markers", name = "該校所屬鄉鎮", marker = list(color = "red")
    ) %>% 
  add_trace(
    x=2,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(鄉鎮基地台) %>% unlist() %>% unname(),
    type="scatter",mode="markers",name = "該校所屬鄉鎮", marker = list(color = "red"))
```

```{r render_plotly6}
render_plotly6 <- renderPlotly
```

```{r output_plotly6}
output_plotly6 <- econ_aging_plot_6_plotly %>% 
  add_trace(
    x=1,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(村里老化指數) %>% unlist() %>% unname(),
    type="scatter",mode="markers", name = "該校所屬村里", marker = list(color = "red")
    ) %>% 
  add_trace(
    x=2,
    y=school_109 %>% filter(縣市學校名稱 == input_selectcity) %>% select(村里老化指數) %>% unlist() %>% unname(),
    type="scatter",mode="markers",name = "該校所屬村里", marker = list(color = "red"))
```

